sonar.projectKey=minhkhoavo_EchoEnglish-nodejs
sonar.organization=kltnute

sonar.projectName=EchoEnglish-nodejs
sonar.projectVersion=1.1


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=./src
sonar.coverage.exclusions=src/**/*.d.ts,src/**/index.ts,src/types/**/*.ts,src/**/*.interface.ts,src/**/*.type.ts,src/config/**/*.ts,src/constants/**/*.ts,src/enum/**/*.ts,src/routes/**/*.ts,src/ai/prompts/**/*.ts,src/controllers/**/*.ts,src/models/**/*.ts,src/dto/**/*.ts
# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8