export enum Domain {
    BUSINESS = 'business',
    OFFICE = 'office',
    FINANCE = 'finance',
    TECHNOLOGY = 'technology',
    EDUCATION = 'education',
    HEALTHCARE = 'healthcare',
    TRAVEL = 'travel',
    HOSPITALITY = 'hospitality',
    MANUFACTURING = 'manufacturing',
    HUMAN_RESOURCES = 'human_resources',
    MARKETING = 'marketing',
    CUSTOMER_SERVICE = 'customer_service',
    LOGISTICS = 'logistics',
    RETAIL = 'retail',
    REAL_ESTATE = 'real_estate',
    LEGAL_COMPLIANCE = 'legal_compliance',
    SAFETY = 'safety',
    NEWS = 'news',
    ENTERTAINMENT = 'entertainment',
    SPORTS = 'sports',
    POLITICS = 'politics',
    ENVIRONMENT = 'environment',
    SCIENCE = 'science',
    MEDIA = 'media',
    LEGAL = 'legal',
    OUTDOOR_RECREATION = 'outdoor_recreation',
    COOKING = 'cooking',
    HOUSE = 'house',
    GENERAL = 'general',
    TECHNICAL = 'technical',
    DAILY_LIFE = 'daily_life',
    HEALTH = 'health',
}

export const AVAILABLE_DOMAINS = Object.values(
    Domain
) satisfies readonly Domain[];
