export enum Domain {
  BUSINESS = "business",
  OFFICE = "office",
  FINANCE = "finance",
  TECHNOLOGY = "technology",
  EDUCATION = "education",
  HEALTHCARE = "healthcare",
  TRAVEL = "travel",
  HOSPITALITY = "hospitality",
  MANUFACTURING = "manufacturing",
  HUMAN_RESOURCES = "human_resources",
  MARKETING = "marketing",
  CUSTOMER_SERVICE = "customer_service",
  LOGISTICS = "logistics",
  RETAIL = "retail",
  REAL_ESTATE = "real_estate",
  LEGAL_COMPLIANCE = "legal_compliance",
  SAFETY = "safety",
}